### ISSUE TITLE
Template logic?

### ISSUE THREAD

**Issue by chrisabrams** [littlstar/starplate#5]
Does this support template logic such as if, each, etc?

**Comment by jwerle** [comment]
Hey @chrisabrams,

Starplate template strings are just [ES6 template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings). You have access to javascript with the `${ ... }` notation. In the event you construct a template string from a template string the `#{ ... }` notation will also work to escape javascript to prevent it from being executed. Consider the following example:

``` js
import { Template } from 'starplate'
let template = new Template(`
  hello #{name}
`)

template.render({name: 'alice'})
```

Using `${name}`  instead of `#{name}` would result in immediate evaluation of the variable `name` where as `#{name}` escapes evaluation instead.

## Simple approach

Logic can be achieved with ternary operators `?:`.
Looping can be achieved with the methods on the `Array` prototype object.

### Ternary logic

``` js
let template = new Template(`
  <span> Hello #{name ? name : 'everyone'} </span>
`)
```

### Array looping

``` js
let template = new Template(`
  <ul>
    #{names.map(name =>  \`<li> #{name} </li>\`)}
  </ul>
`)
```

## Advanced approach

Closures are a good way of representing advanced logic where ternary and array methods are too awkward.

``` js
let template = new Template(`
  <h1>Animals</h1>
  <ul>
  #{(() => {}
    let animals = ['kinkajou', 'monkey', 'raccoon', 'dog']
    let excluded = new Set(['raccoon'])
    let createElement = name => '<li>'+ name +'</li>'
    return animals
    .filter(animal => false == excluded.has(animal))
    .map(animal => createElement(animal))
  )()}
  </ul>
`)
```

**Comment by jwerle** [comment]
@chrisabrams it may be worth it for you to check out https://github.com/littlstar/stardux
You can move logic to [reducers](https://github.com/littlstar/stardux/blob/master/manual/usage.md#reducers) in stardux which are just [redux](https://github.com/rackt/redux) reducers

**Comment by chrisabrams** [comment]
@jwerle best answer I've ever gotten for an issue :+1:

**Comment by jwerle** [comment]
@chrisabrams no problem !
